package stream

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/bestruirui/octopus/internal/transformer/model"
	"github.com/bestruirui/octopus/internal/utils/log"
	"github.com/bestruirui/octopus/internal/utils/safe"
	"github.com/tmaxmax/go-sse"
)

// ErrEmptyUpstreamStream marks 200 SSE streams that ended without forwarding
// any payload (all events skipped by transform or no events at all).
// Relay should fail over to another channel.
var ErrEmptyUpstreamStream = errors.New("upstream stream ended without forwarding any payload")

// ErrDownstreamWriteFailed marks a failure while delivering bytes to the
// downstream client. It must not be treated as evidence that the upstream
// channel is unhealthy.
var ErrDownstreamWriteFailed = errors.New("downstream write failed")

// WrapDownstreamWriteError preserves the writer error chain while adding a
// stable classification for relay accounting.
func WrapDownstreamWriteError(err error) error {
	if err == nil {
		return ErrDownstreamWriteFailed
	}
	return errors.Join(ErrDownstreamWriteFailed, err)
}

// StreamSource abstracts different event sources (SSE, WebSocket, raw bytes).
type StreamSource interface {
	// ReadEvent blocks until the next event is available or returns an error.
	// Returns io.EOF when the stream ends normally.
	ReadEvent(ctx context.Context) ([]byte, error)

	// Close releases resources. Must be idempotent.
	Close() error
}

// StreamTransform converts raw event data to the client's expected format.
// Returns nil/empty slice to skip writing (e.g., keep-alive events).
// For passthrough, set to nil in StreamConfig.
type StreamTransform func(ctx context.Context, data []byte) ([]byte, error)

// StreamTransformResult carries output and an optional protocol-level outcome.
// A terminal failure may include output: the already-started client stream must
// receive that terminal, while the relay still receives a non-nil error.
type StreamTransformResult struct {
	Output     []byte
	Outcome    model.PassthroughTerminalOutcome
	Err        error
	NonPayload bool // Output is transport framing (for example an SSE comment).
}

// StreamTransformWithOutcome is used by raw passthrough streams whose terminal
// event has a result distinct from simply ending the transport.
type StreamTransformWithOutcome func(ctx context.Context, data []byte, payloadWritten bool) StreamTransformResult

// PassthroughTerminalError indicates that a raw protocol terminal completed
// with a non-successful result. It intentionally contains no provider payload;
// Cause carries only bounded, structured classification data when available.
type PassthroughTerminalError struct {
	Outcome model.PassthroughTerminalOutcome
	Cause   error
}

func (e *PassthroughTerminalError) Error() string {
	if e == nil || e.Outcome == model.PassthroughTerminalOutcomeNone {
		return "upstream passthrough terminal failed"
	}
	return fmt.Sprintf("upstream passthrough terminal outcome: %s", e.Outcome)
}

func (e *PassthroughTerminalError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Cause
}

func NewPassthroughTerminalError(outcome model.PassthroughTerminalOutcome, cause ...error) error {
	var unwrapped error
	if len(cause) > 0 {
		unwrapped = cause[0]
	}
	return &PassthroughTerminalError{Outcome: outcome, Cause: unwrapped}
}

// StreamFinalize emits any protocol data that must be written after upstream EOF.
type StreamFinalize func(ctx context.Context) ([]byte, error)

// StreamFinalizeWithOutcome is the outcome-aware form used when finalizing a
// buffered raw event. The outcome is committed only after its output is written.
type StreamFinalizeWithOutcome func(ctx context.Context) StreamTransformResult

// StreamTerminalObserver reports the terminal generated by a stateful inbound
// adapter. The processor samples it only after the corresponding bytes are
// accepted by the downstream writer.
type StreamTerminalObserver func() (model.PassthroughTerminalOutcome, error)

// StreamWriter abstracts the HTTP/WebSocket response writer.
type StreamWriter interface {
	Write(data []byte) (int, error)
	Flush()
	Written() bool
	Header() http.Header
	WriteHeader(code int)
}

// StreamConfig configures a StreamProcessor instance.
type StreamConfig struct {
	// Core dependencies
	Source    StreamSource
	Transform StreamTransform // nil for passthrough
	Writer    StreamWriter
	Context   context.Context

	// Timeout & heartbeat
	FirstTokenTimeout time.Duration // 0 to disable
	HeartbeatInterval time.Duration // 0 to disable
	MaxEventSize      int           // 0 uses the processor default

	// Callbacks
	OnFirstToken        func()                                            // Called when first payload written
	OnFinish            func(ctx context.Context, rawStream []byte) error // Called on stream end
	Finalize            StreamFinalize                                    // Called before OnFinish at stream end
	FinalizeWithOutcome StreamFinalizeWithOutcome                         // Outcome-aware alternative to Finalize
	TerminalObserver    StreamTerminalObserver                            // Samples a written transform terminal

	// IncompleteFinalize handles raw passthrough streams that reached EOF
	// without any TerminalEvents entry after partial payload was written.
	// Requires BufferRawStream and non-empty TerminalEvents. The callback
	// synthesizes protocol terminal bytes which are written to the client,
	// then the processor returns an error wrapping
	// model.ErrIncompleteUpstreamStream. When nil, legacy behavior applies:
	// any non-empty passthrough stream is treated as success.
	IncompleteFinalize func(ctx context.Context, rawStream []byte) ([]byte, error)

	// OnInterrupted synthesizes protocol terminal bytes when the upstream
	// stream breaks with a transport error (not io.EOF, not client disconnect)
	// after partial payload was already written to the client. The callback
	// receives the buffered raw stream (empty when BufferRawStream is off)
	// and, when it returns non-empty bytes, exactly those bytes are written
	// to the client before Run returns an error joining the original read
	// error with the callback error. It is never invoked when the client
	// already received a terminal event, so the client stream ends with at
	// most one protocol terminal. When nil, the stream stays truncated
	// (legacy behavior) and the read error is returned unchanged.
	OnInterrupted func(ctx context.Context, rawStream []byte) ([]byte, error)

	// Passthrough-specific
	BufferRawStream      bool                       // Enable raw stream buffering for metrics
	TerminalEvents       map[string]struct{}        // Protocol terminal events for early completion
	TransformWithOutcome StreamTransformWithOutcome // Optional passthrough transform with explicit outcome
}

// StreamProcessor unifies all stream handling logic.
type StreamProcessor struct {
	config StreamConfig

	// State
	rawBuffer              bytes.Buffer
	payloadWritten         bool
	firstToken             bool
	passthroughOutcome     model.PassthroughTerminalOutcome
	passthroughError       error
	terminalObserverCalled bool
	finalizeDone           bool
	finalizeErr            error
	onFinishDone           bool
	onFinishErr            error
}

// NewStreamProcessor creates a processor from config.
func NewStreamProcessor(config StreamConfig) *StreamProcessor {
	if config.Context == nil {
		config.Context = context.Background()
	}
	return &StreamProcessor{
		config:     config,
		firstToken: true,
	}
}

// errorSignalingSource is implemented by sources whose underlying transport
// must not be reused after a failed stream (e.g. pooled WS connections).
// It lets the processor remove the connection from its pool before the plain
// Close (which would return it for reuse) can run.
type errorSignalingSource interface {
	CloseWithError()
}

// Run executes the unified stream processing loop.
func (p *StreamProcessor) Run() (err error) {
	// Response headers remain provisional until writeOutput or writeHeartbeat
	// commits an actual SSE byte. Empty/error streams can therefore use JSON.
	// Setup heartbeat ticker
	var heartbeatTicker *time.Ticker
	var heartbeatC <-chan time.Time
	if p.config.HeartbeatInterval > 0 {
		heartbeatTicker = time.NewTicker(p.config.HeartbeatInterval)
		heartbeatC = heartbeatTicker.C
		defer heartbeatTicker.Stop()
	}

	// Setup first token timeout
	var firstTokenTimer *time.Timer
	var firstTokenC <-chan time.Time
	if p.firstToken && p.config.FirstTokenTimeout > 0 {
		firstTokenTimer = time.NewTimer(p.config.FirstTokenTimeout)
		firstTokenC = firstTokenTimer.C
		defer func() {
			if firstTokenTimer != nil {
				firstTokenTimer.Stop()
			}
		}()
	}

	markFirstToken := func() {
		if !p.firstToken || !p.payloadWritten {
			return
		}
		p.firstToken = false
		if p.config.OnFirstToken != nil {
			p.config.OnFirstToken()
		}
		if firstTokenTimer != nil {
			if !firstTokenTimer.Stop() {
				select {
				case <-firstTokenTimer.C:
				default:
				}
			}
			firstTokenTimer = nil
			firstTokenC = nil
		}
	}

	// Async read from source — use a derived context so we can unblock on any exit.
	readCtx, readCancel := context.WithCancel(p.config.Context)
	defer func() {
		// Unblock the reader goroutine before closing the source: a pooled WS
		// connection must never be handed back while its previous consumer is
		// still reading from the socket.
		readCancel()
		if err != nil {
			// Error takes priority: remove the underlying connection from its
			// pool (and close it) before Close can return it for reuse.
			if esc, ok := p.config.Source.(errorSignalingSource); ok {
				esc.CloseWithError()
			}
		}
		_ = p.config.Source.Close()
	}()

	type readResult struct {
		data []byte
		err  error
	}
	results := make(chan readResult, 1)
	safe.Go("stream-processor-read", func() {
		defer close(results)
		for {
			data, err := p.config.Source.ReadEvent(readCtx)
			select {
			case results <- readResult{data: data, err: err}:
			case <-readCtx.Done():
				return
			}
			if err != nil {
				return
			}
		}
	})

	// Main event loop
	for {
		select {
		case <-p.config.Context.Done():
			return p.handleDisconnect()

		case <-firstTokenC:
			return p.handleFirstTokenTimeout()

		case <-heartbeatC:
			if err := p.writeHeartbeat(); err != nil {
				return err
			}

		case r, ok := <-results:
			if !ok {
				// Channel closed, stream ended
				return p.finalize()
			}

			if r.err != nil {
				if r.err == io.EOF {
					return p.finalize()
				}
				if errors.Is(r.err, context.Canceled) && p.config.Context.Err() != nil {
					return p.handleDisconnect()
				}
				return p.handleUpstreamInterrupted(r.err)
			}

			if len(r.data) == 0 {
				continue
			}

			// Buffer raw data if enabled
			if p.config.BufferRawStream {
				p.rawBuffer.Write(r.data)
			}

			if err := p.processRawEvent(r.data); err != nil {
				markFirstToken()
				if p.terminalObserved() && p.payloadWritten {
					if finalizeErr := p.finalize(); finalizeErr != nil {
						return errors.Join(err, finalizeErr)
					}
					return err
				}
				return err
			}
			markFirstToken()
			if p.passthroughOutcome != model.PassthroughTerminalOutcomeNone {
				return p.finalize()
			}
		}
	}
}

// processRawEvent applies the optional outcome-aware transform and writes its
// output before returning a protocol-level failure, when one was reported.
func (p *StreamProcessor) processRawEvent(data []byte) error {
	if p.config.TransformWithOutcome != nil {
		result := p.config.TransformWithOutcome(p.config.Context, data, p.payloadWritten)
		return p.commitTransformResult(result)
	}
	return p.processEvent(data)
}

func (p *StreamProcessor) commitTransformResult(result StreamTransformResult) error {
	if len(result.Output) > 0 {
		if writeErr := p.writeOutputClassified(result.Output, !result.NonPayload); writeErr != nil {
			semanticErr := result.Err
			if result.Outcome != model.PassthroughTerminalOutcomeNone &&
				result.Outcome != model.PassthroughTerminalOutcomeCompleted {
				semanticErr = ensurePassthroughTerminalError(result.Outcome, semanticErr)
			}
			if semanticErr != nil {
				return errors.Join(semanticErr, writeErr)
			}
			return writeErr
		}
	}

	// A terminal is committed only after its corresponding payload bytes have
	// been accepted by the downstream writer. Comments and suppressed failure
	// frames may have output bytes without making the attempt non-retryable.
	terminalDelivered := result.Outcome != model.PassthroughTerminalOutcomeNone && len(result.Output) > 0 && !result.NonPayload
	if terminalDelivered {
		p.setPassthroughOutcome(result.Outcome, result.Err)
	}
	if result.Err != nil {
		if terminalDelivered {
			p.passthroughError = result.Err
		}
		if result.Outcome == model.PassthroughTerminalOutcomeFailed && !terminalDelivered {
			return ensurePassthroughTerminalError(result.Outcome, result.Err)
		}
		// A delivered terminal is finalized by Run so OnFinish executes exactly
		// once before the semantic error is returned.
		if terminalDelivered {
			return nil
		}
		return result.Err
	}
	if terminalDelivered && result.Outcome != model.PassthroughTerminalOutcomeCompleted {
		p.passthroughError = ensurePassthroughTerminalError(result.Outcome, nil)
	}
	return nil
}

// processEvent transforms and writes a single event.
func (p *StreamProcessor) processEvent(data []byte) error {
	var output []byte
	var transformErr error
	if p.config.Transform != nil {
		output, transformErr = p.config.Transform(p.config.Context, data)
		if transformErr != nil {
			transformErr = fmt.Errorf("transform error: %w", transformErr)
		}
	} else {
		output = data
	}

	// A transformer may be able to project useful bytes before reporting a
	// semantic error (for example, a delta followed by an error event in one
	// provider frame). Deliver those bytes first; otherwise a visible prefix is
	// silently lost and the processor may append the wrong synthetic terminal.
	if len(output) > 0 {
		if writeErr := p.writeOutput(output); writeErr != nil {
			if transformErr != nil {
				return errors.Join(transformErr, writeErr)
			}
			return writeErr
		}
		// A writer may consume protocol framing without emitting a client-visible
		// frame (WSStreamWriter drops Chat's [DONE] sentinel). Commit a terminal
		// only after this or an earlier write actually became visible downstream.
		if p.payloadWritten {
			if observerErr := p.observeTerminalAfterWrite(); observerErr != nil {
				if transformErr != nil {
					return errors.Join(transformErr, observerErr)
				}
				return observerErr
			}
		}
	}

	if transformErr != nil {
		if p.payloadWritten && p.config.OnInterrupted != nil && !p.terminalObserved() {
			return p.handleTransformInterrupted(transformErr)
		}
		return transformErr
	}
	return nil
}

func (p *StreamProcessor) observeTerminalAfterWrite() error {
	if p.config.TerminalObserver == nil || p.terminalObserverCalled {
		return nil
	}
	outcome, cause := p.config.TerminalObserver()
	if outcome == model.PassthroughTerminalOutcomeNone {
		return cause
	}
	p.terminalObserverCalled = true
	p.setPassthroughOutcome(outcome, cause)
	if outcome != model.PassthroughTerminalOutcomeCompleted {
		return p.passthroughError
	}
	return cause
}

func (p *StreamProcessor) setPassthroughOutcome(outcome model.PassthroughTerminalOutcome, cause error) {
	if outcome == model.PassthroughTerminalOutcomeNone {
		return
	}
	if p.passthroughOutcome != model.PassthroughTerminalOutcomeNone {
		return
	}
	p.passthroughOutcome = outcome
	if outcome != model.PassthroughTerminalOutcomeCompleted {
		p.passthroughError = ensurePassthroughTerminalError(outcome, cause)
		return
	}
	if cause != nil {
		p.passthroughError = cause
	}
}

func ensurePassthroughTerminalError(outcome model.PassthroughTerminalOutcome, cause error) error {
	if cause != nil {
		var terminalErr *PassthroughTerminalError
		if errors.As(cause, &terminalErr) && terminalErr != nil && terminalErr.Outcome == outcome {
			return cause
		}
	}
	return NewPassthroughTerminalError(outcome, cause)
}

func (p *StreamProcessor) markFinalFirstToken(firstPayload bool) {
	if !firstPayload || !p.firstToken {
		return
	}
	p.firstToken = false
	if p.config.OnFirstToken != nil {
		p.config.OnFirstToken()
	}
}

func (p *StreamProcessor) writeOutput(output []byte) error {
	return p.writeOutputClassified(output, true)
}

func (p *StreamProcessor) writeOutputClassified(output []byte, countsAsPayload bool) error {
	if len(output) == 0 {
		return nil
	}
	p.writeSSEHeaders()
	n, err := p.config.Writer.Write(output)
	if err != nil {
		// Writer.Written reports that some earlier frame was accepted. It must
		// not turn a comment-only write into semantic payload, so consult it only
		// for a write that is itself classified as payload.
		if countsAsPayload && (n > 0 || p.config.Writer.Written()) {
			p.payloadWritten = true
		}
		return fmt.Errorf("write error: %w", WrapDownstreamWriteError(err))
	}
	if n < len(output) {
		if countsAsPayload && (n > 0 || p.config.Writer.Written()) {
			p.payloadWritten = true
		}
		return fmt.Errorf("write error: %w", WrapDownstreamWriteError(io.ErrShortWrite))
	}
	if countsAsPayload && p.config.Writer.Written() {
		// A successful Write means the input was consumed, but an adapting
		// writer may intentionally suppress it. Written is the client-visible
		// delivery signal; keep prior visibility sticky across later frames.
		p.payloadWritten = true
	}
	p.config.Writer.Flush()
	return nil
}

func (p *StreamProcessor) writeSSEHeaders() {
	headers := p.config.Writer.Header()
	if headers == nil {
		return
	}
	headers.Set("Content-Type", "text/event-stream")
	headers.Set("Cache-Control", "no-cache")
	headers.Set("Connection", "keep-alive")
	headers.Set("X-Accel-Buffering", "no")
}

// writeHeartbeat sends SSE heartbeat (comment line).
func (p *StreamProcessor) writeHeartbeat() error {
	p.writeSSEHeaders()
	heartbeat := []byte(":\n\n")
	n, err := p.config.Writer.Write(heartbeat)
	if err != nil {
		return WrapDownstreamWriteError(err)
	}
	if n < len(heartbeat) {
		return WrapDownstreamWriteError(io.ErrShortWrite)
	}
	p.config.Writer.Flush()
	return nil
}

// handleDisconnect handles context cancellation or timeout.
func (p *StreamProcessor) handleDisconnect() error {
	// A delivered protocol terminal, including failed/incomplete/cancelled,
	// determines the stream result. Finalize only performs exactly-once cleanup;
	// it must not reinterpret a non-completed terminal as success.
	if p.passthroughOutcome != model.PassthroughTerminalOutcomeNone {
		return p.finalize()
	}
	if p.config.BufferRawStream && len(p.config.TerminalEvents) > 0 && p.streamReachedTerminal() {
		log.Debugf("client disconnected but stream reached terminal event, treating as success")
		return p.finalize()
	}

	err := p.config.Context.Err()
	log.Debugf("client disconnected, stopping stream: written=%t first_token_seen=%t err=%v",
		p.payloadWritten, !p.firstToken, err)

	if p.config.BufferRawStream && p.rawBuffer.Len() > 0 {
		// Still call OnFinish to collect partial metrics.
		if p.config.OnFinish != nil {
			_ = p.config.OnFinish(context.Background(), p.rawBuffer.Bytes())
		}
	}

	return err
}

// handleFirstTokenTimeout returns first token timeout error.
func (p *StreamProcessor) handleFirstTokenTimeout() error {
	log.Warnf("first token timeout (%v), switching channel", p.config.FirstTokenTimeout)
	return fmt.Errorf("first token timeout after %v", p.config.FirstTokenTimeout)
}

// handleUpstreamInterrupted handles a read error that is neither a clean EOF
// nor a client disconnect. Once partial payload is visible to the client the
// attempt is committed: synthesize exactly one protocol terminal via
// OnInterrupted (unless the client already received one), then return an
// error that preserves both the transport error chain and whatever typed
// error the callback reported (typically model.ErrIncompleteUpstreamStream,
// so relay records a hard failure without replaying or failing over).
// handleUpstreamInterrupted handles an upstream read failure after partial
// payload is already visible. The attempt is committed: synthesize exactly one
// protocol terminal via OnInterrupted (unless the client already received one),
// then preserve both the original failure and the callback's typed error.
func (p *StreamProcessor) handleUpstreamInterrupted(readErr error) error {
	return p.handleInterruptedError(fmt.Errorf("stream read error: %w", readErr))
}

func (p *StreamProcessor) handleTransformInterrupted(transformErr error) error {
	return p.handleInterruptedError(fmt.Errorf("stream transform error: %w", transformErr))
}

func (p *StreamProcessor) handleInterruptedError(upstreamErr error) error {
	if p.terminalObserved() {
		// A structured terminal frame can be followed by a pending transport
		// error from a WS reader. Preserve that accounting error, but never emit
		// another protocol terminal or call an adapter finalizer twice.
		if p.passthroughError != nil {
			return errors.Join(p.passthroughError, upstreamErr)
		}
		return upstreamErr
	}
	if !p.payloadWritten || p.config.OnInterrupted == nil {
		return upstreamErr
	}

	output, interruptErr := p.config.OnInterrupted(p.config.Context, p.rawBuffer.Bytes())
	if len(output) > 0 {
		if writeErr := p.writeOutput(output); writeErr != nil {
			// Preserve the callback's typed incomplete sentinel even when the
			// synthesized terminal cannot be sent.
			return errors.Join(upstreamErr, interruptErr, writeErr)
		}
		if errors.Is(interruptErr, model.ErrIncompleteUpstreamStream) {
			p.setPassthroughOutcome(model.PassthroughTerminalOutcomeIncomplete, interruptErr)
		}
		if observerErr := p.observeTerminalAfterWrite(); observerErr != nil {
			return errors.Join(upstreamErr, interruptErr, observerErr)
		}
	}
	if interruptErr != nil {
		return errors.Join(upstreamErr, interruptErr)
	}
	return upstreamErr
}

// finalize completes the stream and calls OnFinish callback.
func (p *StreamProcessor) finalize() (finalErr error) {
	if p.finalizeDone {
		return p.finalizeErr
	}
	p.finalizeDone = true
	defer func() { p.finalizeErr = finalErr }()

	if ctxErr := p.config.Context.Err(); ctxErr != nil && !p.terminalObserved() {
		return ctxErr
	}

	// Once a terminal has been written, do not call an adapter finalizer again.
	// Adapter finalizers mutate aggregation state and must be exactly-once.
	if p.passthroughOutcome != model.PassthroughTerminalOutcomeNone {
		return p.finishWithOnFinish(p.passthroughError)
	}

	if p.config.FinalizeWithOutcome != nil {
		result := p.config.FinalizeWithOutcome(p.config.Context)
		if ctxErr := p.config.Context.Err(); ctxErr != nil && !p.terminalObserved() {
			return ctxErr
		}
		if result.Outcome == model.PassthroughTerminalOutcomeNone &&
			errors.Is(result.Err, model.ErrIncompleteUpstreamStream) && len(result.Output) > 0 {
			result.Outcome = model.PassthroughTerminalOutcomeIncomplete
		}
		if err := p.commitTransformResult(result); err != nil {
			return err
		}
		p.markFinalFirstToken(len(result.Output) > 0)
		if p.passthroughOutcome != model.PassthroughTerminalOutcomeNone {
			return p.finishWithOnFinish(p.passthroughError)
		}
		if result.Err != nil {
			return p.finishWithOnFinish(result.Err)
		}
	} else if p.config.Finalize != nil {
		output, finalizeErr := p.config.Finalize(p.config.Context)
		if ctxErr := p.config.Context.Err(); ctxErr != nil && !p.terminalObserved() {
			return ctxErr
		}
		if err := p.writeOutput(output); err != nil {
			if finalizeErr != nil {
				return errors.Join(finalizeErr, err)
			}
			return err
		}
		if len(output) > 0 && errors.Is(finalizeErr, model.ErrIncompleteUpstreamStream) {
			p.setPassthroughOutcome(model.PassthroughTerminalOutcomeIncomplete, finalizeErr)
		}
		p.markFinalFirstToken(len(output) > 0)
		if finalizeErr != nil {
			return p.finishWithOnFinish(finalizeErr)
		}
	}

	if !p.payloadWritten {
		return ErrEmptyUpstreamStream
	}

	// Raw passthrough streams may have emitted payload but no protocol terminal.
	// Generate one incomplete terminal only after confirming the stream was not
	// merely SSE comments or heartbeat framing.
	if p.config.IncompleteFinalize != nil && p.config.BufferRawStream &&
		len(p.config.TerminalEvents) > 0 && !p.terminalObserved() {
		if ctxErr := p.config.Context.Err(); ctxErr != nil {
			return ctxErr
		}
		output, incompleteErr := p.config.IncompleteFinalize(p.config.Context, p.rawBuffer.Bytes())
		if ctxErr := p.config.Context.Err(); ctxErr != nil {
			return ctxErr
		}
		if err := p.writeOutput(output); err != nil {
			if incompleteErr != nil {
				return errors.Join(incompleteErr, err)
			}
			return err
		}
		if len(output) > 0 {
			p.setPassthroughOutcome(model.PassthroughTerminalOutcomeIncomplete, incompleteErr)
		}
		if incompleteErr == nil {
			incompleteErr = model.ErrIncompleteUpstreamStream
		}
		return p.finishWithOnFinish(incompleteErr)
	}

	return p.finishWithOnFinish(nil)
}

func (p *StreamProcessor) finishWithOnFinish(existing error) error {
	if p.onFinishDone {
		if existing == nil {
			return p.onFinishErr
		}
		if p.onFinishErr == nil {
			return existing
		}
		return errors.Join(existing, p.onFinishErr)
	}
	p.onFinishDone = true
	if p.config.OnFinish != nil {
		p.onFinishErr = p.config.OnFinish(p.config.Context, p.rawBuffer.Bytes())
	}
	if existing == nil {
		return p.onFinishErr
	}
	if p.onFinishErr == nil {
		return existing
	}
	return errors.Join(existing, p.onFinishErr)
}

// PayloadWritten returns whether any payload has been written to the client.
func (p *StreamProcessor) PayloadWritten() bool {
	return p.payloadWritten
}

// RawStream returns a copy of the buffered source bytes.
func (p *StreamProcessor) RawStream() []byte {
	return append([]byte(nil), p.rawBuffer.Bytes()...)
}

// PassthroughOutcome returns the last explicit protocol terminal outcome.
func (p *StreamProcessor) PassthroughOutcome() model.PassthroughTerminalOutcome {
	return p.passthroughOutcome
}

func (p *StreamProcessor) terminalObserved() bool {
	if p.passthroughOutcome != model.PassthroughTerminalOutcomeNone {
		return true
	}
	return p.streamReachedTerminal()
}

// streamReachedTerminal checks if buffered stream contains a terminal event.
func (p *StreamProcessor) streamReachedTerminal() bool {
	if p.rawBuffer.Len() == 0 {
		return false
	}

	maxEventSize := p.config.MaxEventSize
	if maxEventSize <= 0 {
		maxEventSize = 32 * 1024 * 1024
	}
	readCfg := &sse.ReadConfig{MaxEventSize: maxEventSize}
	for ev, err := range sse.Read(bytes.NewReader(p.rawBuffer.Bytes()), readCfg) {
		if err != nil {
			break
		}

		typ := strings.TrimSpace(ev.Type)
		if typ == "" {
			data := ev.Data
			if len(data) > 0 && data[0] == '{' {
				typ = extractJSONType(data)
			}
		}
		if _, ok := p.config.TerminalEvents[typ]; ok {
			return true
		}
	}
	return false
}

// extractJSONType extracts "type" field from JSON without full unmarshaling.
func extractJSONType(data string) string {
	// Simple extraction: find "type":"value"
	if idx := strings.Index(data, `"type"`); idx >= 0 {
		rest := data[idx+6:]
		if idx := strings.IndexByte(rest, ':'); idx >= 0 {
			rest = rest[idx+1:]
			rest = strings.TrimSpace(rest)
			if len(rest) > 0 && rest[0] == '"' {
				rest = rest[1:]
				if idx := strings.IndexByte(rest, '"'); idx >= 0 {
					return rest[:idx]
				}
			}
		}
	}
	return ""
}
